"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-them="light">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Provider store={store}>{children}</Provider>
        </div>
      </body>
    </html>
  );
}
